language: android
dist: trusty

jdk: oraclejdk8

script: "./gradlew clean assembleDebug"

android:
  components:
      - platform-tools
      - tools
      - build-tools-26.0.2
      - android-26
      - extra-android-m2repository
